name: CD

on: 
  workflow_dispatch:
    inputs:
      Deploy:
        required: true
        type: choice
        options:
          - Feature
          - Fix Bug

jobs:
  run_tests:
    runs-on: ubuntu-latest
    permissions:
      # permís d' escriptura
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Run tests Template
      uses: https://ogalceran:${{secrets.TOKEN_REPO}}@github.com/TheGr8Infra/.github/workflows/template_codeverify_runtests.yml