name: CD

on: 
  workflow_call:

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run tests
        uses: ogalceran/DeployGHPages/.github/workflows/template_codeverify_runtests.yml@main