name: CD

on: 
  workflow_dispatch:
  
env:
  REGISTRY: ghcr.io

jobs:
  pull_docker:
    runs-on: ubuntu-latest
    permissions:
      # permís d' escriptura
      contents: write
    steps:
    - name: Install Docker Tools 
      run: |
           curl -fsSL https://get.docker.com -o get-docker.sh
           sh get-docker.sh
    - name: Log in to the Container registry
      uses: docker/login-action@v3.2.0

      with:
        # Apuntem on ho volem DESCARREGAR, en aquest cas al Github Packages
        registry: ${{ env.REGISTRY }}
        # Especifiquem el usuari que executa workflow
        username: ${{ github.actor }}
        # Ens validem  amb el Token del job
        password: ${{ secrets.TOKEN_GHCR }}
        
    - name: Docker Pull Image Calculator
      run: docker pull ghcr.io/ogalceran/dockertesting:v20240718.50

    - name: Commit and push DOCKER IMAGE
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
          commit_message: Push Docker Image
          # li especifico on vui penjar-lo (ruta)
          repository: .
          # Li paso la info del user que farà el commit i el push
          commit_user_name: ogalceran
          commit_user_email: galceranmartinezoriol@gmail.com
                 
    
      
