name: CD

on: 
  workflow_dispatch:
    inputs:
      Deploy:
        required: true
        type: choice
        options:
          - Feature
          - Gas

jobs:
  pull_docker:
    runs-on: ubuntu-latest
    permissions:
      # permís d' escriptura
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4   