name: CD

on: 
  workflow_call:

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Run test
        uses: ogalceran/DeployGHPages/.github/workflows/template_codeverify_runtests.yml@main