name: CD
on: 
  workflow_dispatch:
  pull_request:
    branches: main

jobs:
  run_tests:
    uses: ogalceran/DeployGHPages/.github/workflows/template_codeverify_runtests.yml@main
  
  Deploy_GH_Pages:
    needs: run_tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 20.15.0
      
    - name: Deployment
      uses: JamesIves/github-pages-deploy-action@v4
      with:
       branch: master
       folder: .
         
         
